# Generated by Django 4.2.2 on 2023-06-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('house_size', models.IntegerField()),
                ('schedule_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.house')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.user')),
            ],
        ),
        migrations.CreateModel(
            name='House_composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.user')),
            ],
        ),
    ]
