# Generated by Django 4.2.2 on 2023-06-26 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_house_id_schedule_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 16, 21, 34, 730697))),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.house')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.user')),
            ],
        ),
    ]
