# Generated by Django 4.2.2 on 2023-06-26 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_task_task_description_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 15, 44, 51, 799877)),
        ),
    ]
